/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type RatingType string

// List of RatingType
const (
	USER_RatingType   RatingType = "user"
	CRITIC_RatingType RatingType = "critic"
)
