/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type QualityProfileQualityItemResource struct {
	Id      int32                               `json:"id,omitempty"`
	Name    string                              `json:"name,omitempty"`
	Quality *Quality                            `json:"quality,omitempty"`
	Items   []QualityProfileQualityItemResource `json:"items,omitempty"`
	Allowed bool                                `json:"allowed,omitempty"`
}
