/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ProviderMessageType string

// List of ProviderMessageType
const (
	INFO_ProviderMessageType    ProviderMessageType = "info"
	WARNING_ProviderMessageType ProviderMessageType = "warning"
	ERROR__ProviderMessageType  ProviderMessageType = "error"
)
