/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ProviderMessage struct {
	Message string               `json:"message,omitempty"`
	Type_   *ProviderMessageType `json:"type,omitempty"`
}
