/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type RescanAfterRefreshType string

// List of RescanAfterRefreshType
const (
	ALWAYS_RescanAfterRefreshType       RescanAfterRefreshType = "always"
	AFTER_MANUAL_RescanAfterRefreshType RescanAfterRefreshType = "afterManual"
	NEVER_RescanAfterRefreshType        RescanAfterRefreshType = "never"
)
