/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ImportListBulkResource struct {
	Ids                 []int32          `json:"ids,omitempty"`
	Tags                []int32          `json:"tags,omitempty"`
	ApplyTags           *ApplyTags       `json:"applyTags,omitempty"`
	Enabled             bool             `json:"enabled,omitempty"`
	EnableAuto          bool             `json:"enableAuto,omitempty"`
	RootFolderPath      string           `json:"rootFolderPath,omitempty"`
	QualityProfileId    int32            `json:"qualityProfileId,omitempty"`
	MinimumAvailability *MovieStatusType `json:"minimumAvailability,omitempty"`
}
