/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ExtraFileType string

// List of ExtraFileType
const (
	SUBTITLE_ExtraFileType ExtraFileType = "subtitle"
	METADATA_ExtraFileType ExtraFileType = "metadata"
	OTHER_ExtraFileType    ExtraFileType = "other"
)
