/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type CollectionMovieResource struct {
	TmdbId     int32            `json:"tmdbId,omitempty"`
	ImdbId     string           `json:"imdbId,omitempty"`
	Title      string           `json:"title,omitempty"`
	CleanTitle string           `json:"cleanTitle,omitempty"`
	SortTitle  string           `json:"sortTitle,omitempty"`
	Status     *MovieStatusType `json:"status,omitempty"`
	Overview   string           `json:"overview,omitempty"`
	Runtime    int32            `json:"runtime,omitempty"`
	Images     []MediaCover     `json:"images,omitempty"`
	Year       int32            `json:"year,omitempty"`
	Ratings    *Ratings         `json:"ratings,omitempty"`
	Genres     []string         `json:"genres,omitempty"`
	Folder     string           `json:"folder,omitempty"`
	IsExisting bool             `json:"isExisting,omitempty"`
	IsExcluded bool             `json:"isExcluded,omitempty"`
}
