/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type MediaManagementConfigResource struct {
	Id                                      int32                   `json:"id,omitempty"`
	AutoUnmonitorPreviouslyDownloadedMovies bool                    `json:"autoUnmonitorPreviouslyDownloadedMovies,omitempty"`
	RecycleBin                              string                  `json:"recycleBin,omitempty"`
	RecycleBinCleanupDays                   int32                   `json:"recycleBinCleanupDays,omitempty"`
	DownloadPropersAndRepacks               *ProperDownloadTypes    `json:"downloadPropersAndRepacks,omitempty"`
	CreateEmptyMovieFolders                 bool                    `json:"createEmptyMovieFolders,omitempty"`
	DeleteEmptyFolders                      bool                    `json:"deleteEmptyFolders,omitempty"`
	FileDate                                *FileDateType           `json:"fileDate,omitempty"`
	RescanAfterRefresh                      *RescanAfterRefreshType `json:"rescanAfterRefresh,omitempty"`
	AutoRenameFolders                       bool                    `json:"autoRenameFolders,omitempty"`
	PathsDefaultStatic                      bool                    `json:"pathsDefaultStatic,omitempty"`
	SetPermissionsLinux                     bool                    `json:"setPermissionsLinux,omitempty"`
	ChmodFolder                             string                  `json:"chmodFolder,omitempty"`
	ChownGroup                              string                  `json:"chownGroup,omitempty"`
	SkipFreeSpaceCheckWhenImporting         bool                    `json:"skipFreeSpaceCheckWhenImporting,omitempty"`
	MinimumFreeSpaceWhenImporting           int32                   `json:"minimumFreeSpaceWhenImporting,omitempty"`
	CopyUsingHardlinks                      bool                    `json:"copyUsingHardlinks,omitempty"`
	UseScriptImport                         bool                    `json:"useScriptImport,omitempty"`
	ScriptImportPath                        string                  `json:"scriptImportPath,omitempty"`
	ImportExtraFiles                        bool                    `json:"importExtraFiles,omitempty"`
	ExtraFileExtensions                     string                  `json:"extraFileExtensions,omitempty"`
	EnableMediaInfo                         bool                    `json:"enableMediaInfo,omitempty"`
}
