/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type Field struct {
	Order                       int32          `json:"order,omitempty"`
	Name                        string         `json:"name,omitempty"`
	Label                       string         `json:"label,omitempty"`
	Unit                        string         `json:"unit,omitempty"`
	HelpText                    string         `json:"helpText,omitempty"`
	HelpTextWarning             string         `json:"helpTextWarning,omitempty"`
	HelpLink                    string         `json:"helpLink,omitempty"`
	Type_                       string         `json:"type,omitempty"`
	Advanced                    bool           `json:"advanced,omitempty"`
	SelectOptions               []SelectOption `json:"selectOptions,omitempty"`
	SelectOptionsProviderAction string         `json:"selectOptionsProviderAction,omitempty"`
	Section                     string         `json:"section,omitempty"`
	Hidden                      string         `json:"hidden,omitempty"`
	Privacy                     *PrivacyLevel  `json:"privacy,omitempty"`
	Placeholder                 string         `json:"placeholder,omitempty"`
	IsFloat                     bool           `json:"isFloat,omitempty"`
}
