/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type MetadataConfigResource struct {
	Id                   int32            `json:"id,omitempty"`
	CertificationCountry *TmdbCountryCode `json:"certificationCountry,omitempty"`
}
