/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type RootFolderResource struct {
	Id              int32            `json:"id,omitempty"`
	Path            string           `json:"path,omitempty"`
	Accessible      bool             `json:"accessible,omitempty"`
	FreeSpace       int64            `json:"freeSpace,omitempty"`
	UnmappedFolders []UnmappedFolder `json:"unmappedFolders,omitempty"`
}
