/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

import (
	"time"
)

type SystemResource struct {
	AppName                       string              `json:"appName,omitempty"`
	InstanceName                  string              `json:"instanceName,omitempty"`
	Version                       string              `json:"version,omitempty"`
	BuildTime                     time.Time           `json:"buildTime,omitempty"`
	IsDebug                       bool                `json:"isDebug,omitempty"`
	IsProduction                  bool                `json:"isProduction,omitempty"`
	IsAdmin                       bool                `json:"isAdmin,omitempty"`
	IsUserInteractive             bool                `json:"isUserInteractive,omitempty"`
	StartupPath                   string              `json:"startupPath,omitempty"`
	AppData                       string              `json:"appData,omitempty"`
	OsName                        string              `json:"osName,omitempty"`
	OsVersion                     string              `json:"osVersion,omitempty"`
	IsNetCore                     bool                `json:"isNetCore,omitempty"`
	IsLinux                       bool                `json:"isLinux,omitempty"`
	IsOsx                         bool                `json:"isOsx,omitempty"`
	IsWindows                     bool                `json:"isWindows,omitempty"`
	IsDocker                      bool                `json:"isDocker,omitempty"`
	Mode                          *RuntimeMode        `json:"mode,omitempty"`
	Branch                        string              `json:"branch,omitempty"`
	DatabaseType                  *DatabaseType       `json:"databaseType,omitempty"`
	DatabaseVersion               string              `json:"databaseVersion,omitempty"`
	Authentication                *AuthenticationType `json:"authentication,omitempty"`
	MigrationVersion              int32               `json:"migrationVersion,omitempty"`
	UrlBase                       string              `json:"urlBase,omitempty"`
	RuntimeVersion                string              `json:"runtimeVersion,omitempty"`
	RuntimeName                   string              `json:"runtimeName,omitempty"`
	StartTime                     time.Time           `json:"startTime,omitempty"`
	PackageVersion                string              `json:"packageVersion,omitempty"`
	PackageAuthor                 string              `json:"packageAuthor,omitempty"`
	PackageUpdateMechanism        *UpdateMechanism    `json:"packageUpdateMechanism,omitempty"`
	PackageUpdateMechanismMessage string              `json:"packageUpdateMechanismMessage,omitempty"`
}
