/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type QualityProfileResource struct {
	Id                int32                               `json:"id,omitempty"`
	Name              string                              `json:"name,omitempty"`
	UpgradeAllowed    bool                                `json:"upgradeAllowed,omitempty"`
	Cutoff            int32                               `json:"cutoff,omitempty"`
	Items             []QualityProfileQualityItemResource `json:"items,omitempty"`
	MinFormatScore    int32                               `json:"minFormatScore,omitempty"`
	CutoffFormatScore int32                               `json:"cutoffFormatScore,omitempty"`
	FormatItems       []ProfileFormatItemResource         `json:"formatItems,omitempty"`
	Language          *Language                           `json:"language,omitempty"`
}
