/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ProxyType string

// List of ProxyType
const (
	HTTP_ProxyType   ProxyType = "http"
	SOCKS4_ProxyType ProxyType = "socks4"
	SOCKS5_ProxyType ProxyType = "socks5"
)
