/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type CreditType string

// List of CreditType
const (
	CAST_CreditType CreditType = "cast"
	CREW_CreditType CreditType = "crew"
)
