/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type HealthResource struct {
	Id      int32              `json:"id,omitempty"`
	Source  string             `json:"source,omitempty"`
	Type_   *HealthCheckResult `json:"type,omitempty"`
	Message string             `json:"message,omitempty"`
	WikiUrl *HttpUri           `json:"wikiUrl,omitempty"`
}
