/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type IndexerConfigResource struct {
	Id                       int32  `json:"id,omitempty"`
	MinimumAge               int32  `json:"minimumAge,omitempty"`
	MaximumSize              int32  `json:"maximumSize,omitempty"`
	Retention                int32  `json:"retention,omitempty"`
	RssSyncInterval          int32  `json:"rssSyncInterval,omitempty"`
	PreferIndexerFlags       bool   `json:"preferIndexerFlags,omitempty"`
	AvailabilityDelay        int32  `json:"availabilityDelay,omitempty"`
	AllowHardcodedSubs       bool   `json:"allowHardcodedSubs,omitempty"`
	WhitelistedHardcodedSubs string `json:"whitelistedHardcodedSubs,omitempty"`
}
