/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type AddMovieOptions struct {
	IgnoreEpisodesWithFiles    bool            `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles bool            `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                    *MonitorTypes   `json:"monitor,omitempty"`
	SearchForMovie             bool            `json:"searchForMovie,omitempty"`
	AddMethod                  *AddMovieMethod `json:"addMethod,omitempty"`
}
