/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type SourceType string

// List of SourceType
const (
	TMDB_SourceType     SourceType = "tmdb"
	MAPPINGS_SourceType SourceType = "mappings"
	USER_SourceType     SourceType = "user"
	INDEXER_SourceType  SourceType = "indexer"
)
