/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type QualityModel struct {
	Quality  *Quality  `json:"quality,omitempty"`
	Revision *Revision `json:"revision,omitempty"`
}
