/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type IndexerBulkResource struct {
	Ids                     []int32    `json:"ids,omitempty"`
	Tags                    []int32    `json:"tags,omitempty"`
	ApplyTags               *ApplyTags `json:"applyTags,omitempty"`
	EnableRss               bool       `json:"enableRss,omitempty"`
	EnableAutomaticSearch   bool       `json:"enableAutomaticSearch,omitempty"`
	EnableInteractiveSearch bool       `json:"enableInteractiveSearch,omitempty"`
	Priority                int32      `json:"priority,omitempty"`
}
