/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type RejectionType string

// List of RejectionType
const (
	PERMANENT_RejectionType RejectionType = "permanent"
	TEMPORARY_RejectionType RejectionType = "temporary"
)
