/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type AddMovieMethod string

// List of AddMovieMethod
const (
	MANUAL_AddMovieMethod     AddMovieMethod = "manual"
	LIST_AddMovieMethod       AddMovieMethod = "list"
	COLLECTION_AddMovieMethod AddMovieMethod = "collection"
)
