/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type QualitySource string

// List of QualitySource
const (
	UNKNOWN_QualitySource   QualitySource = "unknown"
	CAM_QualitySource       QualitySource = "cam"
	TELESYNC_QualitySource  QualitySource = "telesync"
	TELECINE_QualitySource  QualitySource = "telecine"
	WORKPRINT_QualitySource QualitySource = "workprint"
	DVD_QualitySource       QualitySource = "dvd"
	TV_QualitySource        QualitySource = "tv"
	WEBDL_QualitySource     QualitySource = "webdl"
	WEBRIP_QualitySource    QualitySource = "webrip"
	BLURAY_QualitySource    QualitySource = "bluray"
)
