/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type CommandPriority string

// List of CommandPriority
const (
	NORMAL_CommandPriority CommandPriority = "normal"
	HIGH_CommandPriority   CommandPriority = "high"
	LOW_CommandPriority    CommandPriority = "low"
)
