/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ProfileFormatItemResource struct {
	Id     int32  `json:"id,omitempty"`
	Format int32  `json:"format,omitempty"`
	Name   string `json:"name,omitempty"`
	Score  int32  `json:"score,omitempty"`
}
