/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type CommandTrigger string

// List of CommandTrigger
const (
	UNSPECIFIED_CommandTrigger CommandTrigger = "unspecified"
	MANUAL_CommandTrigger      CommandTrigger = "manual"
	SCHEDULED_CommandTrigger   CommandTrigger = "scheduled"
)
