/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type MovieFileListResource struct {
	MovieFileIds []int32       `json:"movieFileIds,omitempty"`
	Languages    []Language    `json:"languages,omitempty"`
	Quality      *QualityModel `json:"quality,omitempty"`
	Edition      string        `json:"edition,omitempty"`
	ReleaseGroup string        `json:"releaseGroup,omitempty"`
	SceneName    string        `json:"sceneName,omitempty"`
	IndexerFlags int32         `json:"indexerFlags,omitempty"`
}
