/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type Quality struct {
	Id         int32          `json:"id,omitempty"`
	Name       string         `json:"name,omitempty"`
	Source     *QualitySource `json:"source,omitempty"`
	Resolution int32          `json:"resolution,omitempty"`
	Modifier   *Modifier      `json:"modifier,omitempty"`
}
