/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type ParseResource struct {
	Id                int32                  `json:"id,omitempty"`
	Title             string                 `json:"title,omitempty"`
	ParsedMovieInfo   *ParsedMovieInfo       `json:"parsedMovieInfo,omitempty"`
	Movie             *MovieResource         `json:"movie,omitempty"`
	Languages         []Language             `json:"languages,omitempty"`
	CustomFormats     []CustomFormatResource `json:"customFormats,omitempty"`
	CustomFormatScore int32                  `json:"customFormatScore,omitempty"`
}
