/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type CollectionUpdateResource struct {
	CollectionIds       []int32          `json:"collectionIds,omitempty"`
	Monitored           bool             `json:"monitored,omitempty"`
	MonitorMovies       bool             `json:"monitorMovies,omitempty"`
	SearchOnAdd         bool             `json:"searchOnAdd,omitempty"`
	QualityProfileId    int32            `json:"qualityProfileId,omitempty"`
	RootFolderPath      string           `json:"rootFolderPath,omitempty"`
	MinimumAvailability *MovieStatusType `json:"minimumAvailability,omitempty"`
}
