/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type PrivacyLevel string

// List of PrivacyLevel
const (
	NORMAL_PrivacyLevel    PrivacyLevel = "normal"
	PASSWORD_PrivacyLevel  PrivacyLevel = "password"
	API_KEY_PrivacyLevel   PrivacyLevel = "apiKey"
	USER_NAME_PrivacyLevel PrivacyLevel = "userName"
)
