/*
 * Radarr
 *
 * Radarr API docs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientRadarr

type DatabaseType string

// List of DatabaseType
const (
	SQ_LITE_DatabaseType     DatabaseType = "sqLite"
	POSTGRE_SQL_DatabaseType DatabaseType = "postgreSQL"
)
