/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MediaRequest struct {
	Id float64 `json:"id"`
	// Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
	Status float64 `json:"status"`
	Media *MediaInfo `json:"media,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	RequestedBy *User `json:"requestedBy,omitempty"`
	ModifiedBy *AnyOfMediaRequestModifiedBy `json:"modifiedBy,omitempty"`
	Is4k bool `json:"is4k,omitempty"`
	ServerId float64 `json:"serverId,omitempty"`
	ProfileId float64 `json:"profileId,omitempty"`
	RootFolder string `json:"rootFolder,omitempty"`
}
