/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MovieDetails struct {
	Id float64 `json:"id,omitempty"`
	ImdbId string `json:"imdbId,omitempty"`
	Adult bool `json:"adult,omitempty"`
	BackdropPath string `json:"backdropPath,omitempty"`
	PosterPath string `json:"posterPath,omitempty"`
	Budget float64 `json:"budget,omitempty"`
	Genres []Genre `json:"genres,omitempty"`
	Homepage string `json:"homepage,omitempty"`
	RelatedVideos []RelatedVideo `json:"relatedVideos,omitempty"`
	OriginalLanguage string `json:"originalLanguage,omitempty"`
	OriginalTitle string `json:"originalTitle,omitempty"`
	Overview string `json:"overview,omitempty"`
	Popularity float64 `json:"popularity,omitempty"`
	ProductionCompanies []ProductionCompany `json:"productionCompanies,omitempty"`
	ProductionCountries []MovieDetailsProductionCountries `json:"productionCountries,omitempty"`
	ReleaseDate string `json:"releaseDate,omitempty"`
	Releases *MovieDetailsReleases `json:"releases,omitempty"`
	Revenue float64 `json:"revenue,omitempty"`
	Runtime float64 `json:"runtime,omitempty"`
	SpokenLanguages []SpokenLanguage `json:"spokenLanguages,omitempty"`
	Status string `json:"status,omitempty"`
	Tagline string `json:"tagline,omitempty"`
	Title string `json:"title,omitempty"`
	Video bool `json:"video,omitempty"`
	VoteAverage float64 `json:"voteAverage,omitempty"`
	VoteCount float64 `json:"voteCount,omitempty"`
	Credits *MovieDetailsCredits `json:"credits,omitempty"`
	Collection *MovieDetailsCollection `json:"collection,omitempty"`
	ExternalIds *ExternalIds `json:"externalIds,omitempty"`
	MediaInfo *MediaInfo `json:"mediaInfo,omitempty"`
	WatchProviders [][]WatchProvidersInner `json:"watchProviders,omitempty"`
}
