/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Episode struct {
	Id float64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	AirDate string `json:"airDate,omitempty"`
	EpisodeNumber float64 `json:"episodeNumber,omitempty"`
	Overview string `json:"overview,omitempty"`
	ProductionCode string `json:"productionCode,omitempty"`
	SeasonNumber float64 `json:"seasonNumber,omitempty"`
	ShowId float64 `json:"showId,omitempty"`
	StillPath string `json:"stillPath,omitempty"`
	VoteAverage float64 `json:"voteAverage,omitempty"`
	VoteCount float64 `json:"voteCount,omitempty"`
}
