/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientOverseerr

type CreditCast struct {
	Id               float64    `json:"id,omitempty"`
	OriginalLanguage string     `json:"originalLanguage,omitempty"`
	EpisodeCount     float64    `json:"episodeCount,omitempty"`
	Overview         string     `json:"overview,omitempty"`
	OriginCountry    []string   `json:"originCountry,omitempty"`
	OriginalName     string     `json:"originalName,omitempty"`
	VoteCount        float64    `json:"voteCount,omitempty"`
	Name             string     `json:"name,omitempty"`
	MediaType        string     `json:"mediaType,omitempty"`
	Popularity       float64    `json:"popularity,omitempty"`
	CreditId         string     `json:"creditId,omitempty"`
	BackdropPath     string     `json:"backdropPath,omitempty"`
	FirstAirDate     string     `json:"firstAirDate,omitempty"`
	VoteAverage      float64    `json:"voteAverage,omitempty"`
	GenreIds         []float64  `json:"genreIds,omitempty"`
	PosterPath       string     `json:"posterPath,omitempty"`
	OriginalTitle    string     `json:"originalTitle,omitempty"`
	Video            bool       `json:"video,omitempty"`
	Title            string     `json:"title,omitempty"`
	Adult            bool       `json:"adult,omitempty"`
	ReleaseDate      string     `json:"releaseDate,omitempty"`
	Character        string     `json:"character,omitempty"`
	MediaInfo        *MediaInfo `json:"mediaInfo,omitempty"`
}
