/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientOverseerr

type SonarrSeries struct {
	Title             string                   `json:"title,omitempty"`
	SortTitle         string                   `json:"sortTitle,omitempty"`
	SeasonCount       float64                  `json:"seasonCount,omitempty"`
	Status            string                   `json:"status,omitempty"`
	Overview          string                   `json:"overview,omitempty"`
	Network           string                   `json:"network,omitempty"`
	AirTime           string                   `json:"airTime,omitempty"`
	Images            []SonarrSeriesImages     `json:"images,omitempty"`
	RemotePoster      string                   `json:"remotePoster,omitempty"`
	Seasons           []SonarrSeriesSeasons    `json:"seasons,omitempty"`
	Year              float64                  `json:"year,omitempty"`
	Path              string                   `json:"path,omitempty"`
	ProfileId         float64                  `json:"profileId,omitempty"`
	LanguageProfileId float64                  `json:"languageProfileId,omitempty"`
	SeasonFolder      bool                     `json:"seasonFolder,omitempty"`
	Monitored         bool                     `json:"monitored,omitempty"`
	UseSceneNumbering bool                     `json:"useSceneNumbering,omitempty"`
	Runtime           float64                  `json:"runtime,omitempty"`
	TvdbId            float64                  `json:"tvdbId,omitempty"`
	TvRageId          float64                  `json:"tvRageId,omitempty"`
	TvMazeId          float64                  `json:"tvMazeId,omitempty"`
	FirstAired        string                   `json:"firstAired,omitempty"`
	LastInfoSync      string                   `json:"lastInfoSync,omitempty"`
	SeriesType        string                   `json:"seriesType,omitempty"`
	CleanTitle        string                   `json:"cleanTitle,omitempty"`
	ImdbId            string                   `json:"imdbId,omitempty"`
	TitleSlug         string                   `json:"titleSlug,omitempty"`
	Certification     string                   `json:"certification,omitempty"`
	Genres            []string                 `json:"genres,omitempty"`
	Tags              []string                 `json:"tags,omitempty"`
	Added             string                   `json:"added,omitempty"`
	Ratings           []SonarrSeriesRatings    `json:"ratings,omitempty"`
	QualityProfileId  float64                  `json:"qualityProfileId,omitempty"`
	Id                float64                  `json:"id,omitempty"`
	RootFolderPath    string                   `json:"rootFolderPath,omitempty"`
	AddOptions        []SonarrSeriesAddOptions `json:"addOptions,omitempty"`
}
