/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TvDetails struct {
	Id float64 `json:"id,omitempty"`
	BackdropPath string `json:"backdropPath,omitempty"`
	PosterPath string `json:"posterPath,omitempty"`
	ContentRatings *TvDetailsContentRatings `json:"contentRatings,omitempty"`
	CreatedBy []TvDetailsCreatedBy `json:"createdBy,omitempty"`
	EpisodeRunTime []float64 `json:"episodeRunTime,omitempty"`
	FirstAirDate string `json:"firstAirDate,omitempty"`
	Genres []Genre `json:"genres,omitempty"`
	Homepage string `json:"homepage,omitempty"`
	InProduction bool `json:"inProduction,omitempty"`
	Languages []string `json:"languages,omitempty"`
	LastAirDate string `json:"lastAirDate,omitempty"`
	LastEpisodeToAir *Episode `json:"lastEpisodeToAir,omitempty"`
	Name string `json:"name,omitempty"`
	NextEpisodeToAir *Episode `json:"nextEpisodeToAir,omitempty"`
	Networks []ProductionCompany `json:"networks,omitempty"`
	NumberOfEpisodes float64 `json:"numberOfEpisodes,omitempty"`
	NumberOfSeason float64 `json:"numberOfSeason,omitempty"`
	OriginCountry []string `json:"originCountry,omitempty"`
	OriginalLanguage string `json:"originalLanguage,omitempty"`
	OriginalName string `json:"originalName,omitempty"`
	Overview string `json:"overview,omitempty"`
	Popularity float64 `json:"popularity,omitempty"`
	ProductionCompanies []ProductionCompany `json:"productionCompanies,omitempty"`
	ProductionCountries []MovieDetailsProductionCountries `json:"productionCountries,omitempty"`
	SpokenLanguages []SpokenLanguage `json:"spokenLanguages,omitempty"`
	Seasons []Season `json:"seasons,omitempty"`
	Status string `json:"status,omitempty"`
	Tagline string `json:"tagline,omitempty"`
	Type_ string `json:"type,omitempty"`
	VoteAverage float64 `json:"voteAverage,omitempty"`
	VoteCount float64 `json:"voteCount,omitempty"`
	Credits *MovieDetailsCredits `json:"credits,omitempty"`
	ExternalIds *ExternalIds `json:"externalIds,omitempty"`
	Keywords []Keyword `json:"keywords,omitempty"`
	MediaInfo *MediaInfo `json:"mediaInfo,omitempty"`
	WatchProviders [][]WatchProvidersInner `json:"watchProviders,omitempty"`
}
