/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type HistoryResource struct {
	Id                  int32                    `json:"id,omitempty"`
	EpisodeId           int32                    `json:"episodeId,omitempty"`
	SeriesId            int32                    `json:"seriesId,omitempty"`
	SourceTitle         string                   `json:"sourceTitle,omitempty"`
	Languages           []Language               `json:"languages,omitempty"`
	Quality             *QualityModel            `json:"quality,omitempty"`
	CustomFormats       []CustomFormatResource   `json:"customFormats,omitempty"`
	CustomFormatScore   int32                    `json:"customFormatScore,omitempty"`
	QualityCutoffNotMet bool                     `json:"qualityCutoffNotMet,omitempty"`
	Date                time.Time                `json:"date,omitempty"`
	DownloadId          string                   `json:"downloadId,omitempty"`
	EventType           *EpisodeHistoryEventType `json:"eventType,omitempty"`
	Data                map[string]string        `json:"data,omitempty"`
	Episode             *EpisodeResource         `json:"episode,omitempty"`
	Series              *SeriesResource          `json:"series,omitempty"`
}
