/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type SeriesEditorResource struct {
	SeriesIds              []int32              `json:"seriesIds,omitempty"`
	Monitored              bool                 `json:"monitored,omitempty"`
	MonitorNewItems        *NewItemMonitorTypes `json:"monitorNewItems,omitempty"`
	QualityProfileId       int32                `json:"qualityProfileId,omitempty"`
	SeriesType             *SeriesTypes         `json:"seriesType,omitempty"`
	SeasonFolder           bool                 `json:"seasonFolder,omitempty"`
	RootFolderPath         string               `json:"rootFolderPath,omitempty"`
	Tags                   []int32              `json:"tags,omitempty"`
	ApplyTags              *ApplyTags           `json:"applyTags,omitempty"`
	MoveFiles              bool                 `json:"moveFiles,omitempty"`
	DeleteFiles            bool                 `json:"deleteFiles,omitempty"`
	AddImportListExclusion bool                 `json:"addImportListExclusion,omitempty"`
}
