/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type BackupResource struct {
	Id    int32       `json:"id,omitempty"`
	Name  string      `json:"name,omitempty"`
	Path  string      `json:"path,omitempty"`
	Type_ *BackupType `json:"type,omitempty"`
	Size  int64       `json:"size,omitempty"`
	Time  time.Time   `json:"time,omitempty"`
}
