/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type Command struct {
	SendUpdatesToClient bool            `json:"sendUpdatesToClient,omitempty"`
	UpdateScheduledTask bool            `json:"updateScheduledTask,omitempty"`
	CompletionMessage   string          `json:"completionMessage,omitempty"`
	RequiresDiskAccess  bool            `json:"requiresDiskAccess,omitempty"`
	IsExclusive         bool            `json:"isExclusive,omitempty"`
	IsLongRunning       bool            `json:"isLongRunning,omitempty"`
	Name                string          `json:"name,omitempty"`
	LastExecutionTime   time.Time       `json:"lastExecutionTime,omitempty"`
	LastStartTime       time.Time       `json:"lastStartTime,omitempty"`
	Trigger             *CommandTrigger `json:"trigger,omitempty"`
	SuppressMessages    bool            `json:"suppressMessages,omitempty"`
	ClientUserAgent     string          `json:"clientUserAgent,omitempty"`
}
