/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type MetadataResource struct {
	Id                 int32              `json:"id,omitempty"`
	Name               string             `json:"name,omitempty"`
	Fields             []Field            `json:"fields,omitempty"`
	ImplementationName string             `json:"implementationName,omitempty"`
	Implementation     string             `json:"implementation,omitempty"`
	ConfigContract     string             `json:"configContract,omitempty"`
	InfoLink           string             `json:"infoLink,omitempty"`
	Message            *ProviderMessage   `json:"message,omitempty"`
	Tags               []int32            `json:"tags,omitempty"`
	Presets            []MetadataResource `json:"presets,omitempty"`
	Enable             bool               `json:"enable,omitempty"`
}
