/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type TrackedDownloadState string

// List of TrackedDownloadState
const (
	DOWNLOADING_TrackedDownloadState    TrackedDownloadState = "downloading"
	IMPORT_BLOCKED_TrackedDownloadState TrackedDownloadState = "importBlocked"
	IMPORT_PENDING_TrackedDownloadState TrackedDownloadState = "importPending"
	IMPORTING_TrackedDownloadState      TrackedDownloadState = "importing"
	IMPORTED_TrackedDownloadState       TrackedDownloadState = "imported"
	FAILED_PENDING_TrackedDownloadState TrackedDownloadState = "failedPending"
	FAILED_TrackedDownloadState         TrackedDownloadState = "failed"
	IGNORED_TrackedDownloadState        TrackedDownloadState = "ignored"
)
