/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type TaskResource struct {
	Id            int32     `json:"id,omitempty"`
	Name          string    `json:"name,omitempty"`
	TaskName      string    `json:"taskName,omitempty"`
	Interval      int32     `json:"interval,omitempty"`
	LastExecution time.Time `json:"lastExecution,omitempty"`
	LastStartTime time.Time `json:"lastStartTime,omitempty"`
	NextExecution time.Time `json:"nextExecution,omitempty"`
	LastDuration  string    `json:"lastDuration,omitempty"`
}
