/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type LogResource struct {
	Id            int32     `json:"id,omitempty"`
	Time          time.Time `json:"time,omitempty"`
	Exception     string    `json:"exception,omitempty"`
	ExceptionType string    `json:"exceptionType,omitempty"`
	Level         string    `json:"level,omitempty"`
	Logger        string    `json:"logger,omitempty"`
	Message       string    `json:"message,omitempty"`
	Method        string    `json:"method,omitempty"`
}
