/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type SeriesStatisticsResource struct {
	SeasonCount       int32    `json:"seasonCount,omitempty"`
	EpisodeFileCount  int32    `json:"episodeFileCount,omitempty"`
	EpisodeCount      int32    `json:"episodeCount,omitempty"`
	TotalEpisodeCount int32    `json:"totalEpisodeCount,omitempty"`
	SizeOnDisk        int64    `json:"sizeOnDisk,omitempty"`
	ReleaseGroups     []string `json:"releaseGroups,omitempty"`
	PercentOfEpisodes float64  `json:"percentOfEpisodes,omitempty"`
}
