/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type NamingConfigResource struct {
	Id                           int32  `json:"id,omitempty"`
	RenameEpisodes               bool   `json:"renameEpisodes,omitempty"`
	ReplaceIllegalCharacters     bool   `json:"replaceIllegalCharacters,omitempty"`
	ColonReplacementFormat       int32  `json:"colonReplacementFormat,omitempty"`
	CustomColonReplacementFormat string `json:"customColonReplacementFormat,omitempty"`
	MultiEpisodeStyle            int32  `json:"multiEpisodeStyle,omitempty"`
	StandardEpisodeFormat        string `json:"standardEpisodeFormat,omitempty"`
	DailyEpisodeFormat           string `json:"dailyEpisodeFormat,omitempty"`
	AnimeEpisodeFormat           string `json:"animeEpisodeFormat,omitempty"`
	SeriesFolderFormat           string `json:"seriesFolderFormat,omitempty"`
	SeasonFolderFormat           string `json:"seasonFolderFormat,omitempty"`
	SpecialsFolderFormat         string `json:"specialsFolderFormat,omitempty"`
}
