/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type UpdateResource struct {
	Id          int32          `json:"id,omitempty"`
	Version     string         `json:"version,omitempty"`
	Branch      string         `json:"branch,omitempty"`
	ReleaseDate time.Time      `json:"releaseDate,omitempty"`
	FileName    string         `json:"fileName,omitempty"`
	Url         string         `json:"url,omitempty"`
	Installed   bool           `json:"installed,omitempty"`
	InstalledOn time.Time      `json:"installedOn,omitempty"`
	Installable bool           `json:"installable,omitempty"`
	Latest      bool           `json:"latest,omitempty"`
	Changes     *UpdateChanges `json:"changes,omitempty"`
	Hash        string         `json:"hash,omitempty"`
}
