/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type ReleaseProfileResource struct {
	Id        int32   `json:"id,omitempty"`
	Name      string  `json:"name,omitempty"`
	Enabled   bool    `json:"enabled,omitempty"`
	IndexerId int32   `json:"indexerId,omitempty"`
	Tags      []int32 `json:"tags,omitempty"`
}
