/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type QueueStatusResource struct {
	Id              int32 `json:"id,omitempty"`
	TotalCount      int32 `json:"totalCount,omitempty"`
	Count           int32 `json:"count,omitempty"`
	UnknownCount    int32 `json:"unknownCount,omitempty"`
	Errors          bool  `json:"errors,omitempty"`
	Warnings        bool  `json:"warnings,omitempty"`
	UnknownErrors   bool  `json:"unknownErrors,omitempty"`
	UnknownWarnings bool  `json:"unknownWarnings,omitempty"`
}
