/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

import (
	"time"
)

type ReleaseResource struct {
	Id                           int32                    `json:"id,omitempty"`
	Guid                         string                   `json:"guid,omitempty"`
	Quality                      *QualityModel            `json:"quality,omitempty"`
	QualityWeight                int32                    `json:"qualityWeight,omitempty"`
	Age                          int32                    `json:"age,omitempty"`
	AgeHours                     float64                  `json:"ageHours,omitempty"`
	AgeMinutes                   float64                  `json:"ageMinutes,omitempty"`
	Size                         int64                    `json:"size,omitempty"`
	IndexerId                    int32                    `json:"indexerId,omitempty"`
	Indexer                      string                   `json:"indexer,omitempty"`
	ReleaseGroup                 string                   `json:"releaseGroup,omitempty"`
	SubGroup                     string                   `json:"subGroup,omitempty"`
	ReleaseHash                  string                   `json:"releaseHash,omitempty"`
	Title                        string                   `json:"title,omitempty"`
	FullSeason                   bool                     `json:"fullSeason,omitempty"`
	SceneSource                  bool                     `json:"sceneSource,omitempty"`
	SeasonNumber                 int32                    `json:"seasonNumber,omitempty"`
	Languages                    []Language               `json:"languages,omitempty"`
	LanguageWeight               int32                    `json:"languageWeight,omitempty"`
	AirDate                      string                   `json:"airDate,omitempty"`
	SeriesTitle                  string                   `json:"seriesTitle,omitempty"`
	EpisodeNumbers               []int32                  `json:"episodeNumbers,omitempty"`
	AbsoluteEpisodeNumbers       []int32                  `json:"absoluteEpisodeNumbers,omitempty"`
	MappedSeasonNumber           int32                    `json:"mappedSeasonNumber,omitempty"`
	MappedEpisodeNumbers         []int32                  `json:"mappedEpisodeNumbers,omitempty"`
	MappedAbsoluteEpisodeNumbers []int32                  `json:"mappedAbsoluteEpisodeNumbers,omitempty"`
	MappedSeriesId               int32                    `json:"mappedSeriesId,omitempty"`
	MappedEpisodeInfo            []ReleaseEpisodeResource `json:"mappedEpisodeInfo,omitempty"`
	Approved                     bool                     `json:"approved,omitempty"`
	TemporarilyRejected          bool                     `json:"temporarilyRejected,omitempty"`
	Rejected                     bool                     `json:"rejected,omitempty"`
	TvdbId                       int32                    `json:"tvdbId,omitempty"`
	TvRageId                     int32                    `json:"tvRageId,omitempty"`
	ImdbId                       string                   `json:"imdbId,omitempty"`
	Rejections                   []string                 `json:"rejections,omitempty"`
	PublishDate                  time.Time                `json:"publishDate,omitempty"`
	CommentUrl                   string                   `json:"commentUrl,omitempty"`
	DownloadUrl                  string                   `json:"downloadUrl,omitempty"`
	InfoUrl                      string                   `json:"infoUrl,omitempty"`
	EpisodeRequested             bool                     `json:"episodeRequested,omitempty"`
	DownloadAllowed              bool                     `json:"downloadAllowed,omitempty"`
	ReleaseWeight                int32                    `json:"releaseWeight,omitempty"`
	CustomFormats                []CustomFormatResource   `json:"customFormats,omitempty"`
	CustomFormatScore            int32                    `json:"customFormatScore,omitempty"`
	SceneMapping                 *AlternateTitleResource  `json:"sceneMapping,omitempty"`
	MagnetUrl                    string                   `json:"magnetUrl,omitempty"`
	InfoHash                     string                   `json:"infoHash,omitempty"`
	Seeders                      int32                    `json:"seeders,omitempty"`
	Leechers                     int32                    `json:"leechers,omitempty"`
	Protocol                     *DownloadProtocol        `json:"protocol,omitempty"`
	IndexerFlags                 int32                    `json:"indexerFlags,omitempty"`
	IsDaily                      bool                     `json:"isDaily,omitempty"`
	IsAbsoluteNumbering          bool                     `json:"isAbsoluteNumbering,omitempty"`
	IsPossibleSpecialEpisode     bool                     `json:"isPossibleSpecialEpisode,omitempty"`
	Special                      bool                     `json:"special,omitempty"`
	SeriesId                     int32                    `json:"seriesId,omitempty"`
	EpisodeId                    int32                    `json:"episodeId,omitempty"`
	EpisodeIds                   []int32                  `json:"episodeIds,omitempty"`
	DownloadClientId             int32                    `json:"downloadClientId,omitempty"`
	DownloadClient               string                   `json:"downloadClient,omitempty"`
	ShouldOverride               bool                     `json:"shouldOverride,omitempty"`
}
