/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type EpisodeHistoryEventType string

// List of EpisodeHistoryEventType
const (
	UNKNOWN_EpisodeHistoryEventType                  EpisodeHistoryEventType = "unknown"
	GRABBED_EpisodeHistoryEventType                  EpisodeHistoryEventType = "grabbed"
	SERIES_FOLDER_IMPORTED_EpisodeHistoryEventType   EpisodeHistoryEventType = "seriesFolderImported"
	DOWNLOAD_FOLDER_IMPORTED_EpisodeHistoryEventType EpisodeHistoryEventType = "downloadFolderImported"
	DOWNLOAD_FAILED_EpisodeHistoryEventType          EpisodeHistoryEventType = "downloadFailed"
	EPISODE_FILE_DELETED_EpisodeHistoryEventType     EpisodeHistoryEventType = "episodeFileDeleted"
	EPISODE_FILE_RENAMED_EpisodeHistoryEventType     EpisodeHistoryEventType = "episodeFileRenamed"
	DOWNLOAD_IGNORED_EpisodeHistoryEventType         EpisodeHistoryEventType = "downloadIgnored"
)
