/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swaggerClientSonarr

type MediaInfoResource struct {
	Id                    int32   `json:"id,omitempty"`
	AudioBitrate          int64   `json:"audioBitrate,omitempty"`
	AudioChannels         float64 `json:"audioChannels,omitempty"`
	AudioCodec            string  `json:"audioCodec,omitempty"`
	AudioLanguages        string  `json:"audioLanguages,omitempty"`
	AudioStreamCount      int32   `json:"audioStreamCount,omitempty"`
	VideoBitDepth         int32   `json:"videoBitDepth,omitempty"`
	VideoBitrate          int64   `json:"videoBitrate,omitempty"`
	VideoCodec            string  `json:"videoCodec,omitempty"`
	VideoFps              float64 `json:"videoFps,omitempty"`
	VideoDynamicRange     string  `json:"videoDynamicRange,omitempty"`
	VideoDynamicRangeType string  `json:"videoDynamicRangeType,omitempty"`
	Resolution            string  `json:"resolution,omitempty"`
	RunTime               string  `json:"runTime,omitempty"`
	ScanType              string  `json:"scanType,omitempty"`
	Subtitles             string  `json:"subtitles,omitempty"`
}
